# Generated by Django 5.1.6 on 2025-09-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Tanzeel Foundation", max_length=255),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="info@tanzeelfoundation.org", max_length=254
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Config",
                "verbose_name_plural": "Site Config",
            },
        ),
        migrations.DeleteModel(
            name="SiteSettings",
        ),
    ]
