# Generated by Django 5.1.6 on 2025-09-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_siteconfig_delete_sitesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foundation_name",
                    models.CharField(default="Tanzeel Foundation", max_length=255),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="info@tanzeelfoundation.org", max_length=254
                    ),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("mission_statement", models.TextField(blank=True)),
                ("vision_statement", models.TextField(blank=True)),
                ("about_us", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="favicons/"),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.DeleteModel(
            name="SiteConfig",
        ),
    ]
