# Generated by Django 6.0 on 2025-12-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('mobile', 'Mobile Pay')], max_length=20),
        ),
    ]
