# Generated by Django 6.0.1 on 2026-05-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_donation_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='info@tanzeelfoundation.co.tz', max_length=254),
        ),
    ]
