# Generated by Django 5.1.6 on 2025-09-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="homepage_images/")),
                ("small_title", models.CharField(max_length=15)),
                ("large_title", models.CharField(max_length=30)),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional: A link for the 'Read More' button.",
                    ),
                ),
                (
                    "event_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional: Date of the event if applicable.",
                        null=True,
                    ),
                ),
                (
                    "event_location",
                    models.CharField(blank=True, help_text="Optional", max_length=255),
                ),
                (
                    "event_time",
                    models.TimeField(blank=True, help_text="Optional", null=True),
                ),
                ("aprove", models.BooleanField(default=False)),
            ],
        ),
    ]
