# Generated by Django 6.0.1 on 2026-02-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_us_division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('aprove', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='About_us_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='About_us_team/')),
                ('linkedin_link_url', models.CharField(blank=True, help_text='Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).', max_length=200)),
                ('twitter_link_url', models.CharField(blank=True, help_text='Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).', max_length=200)),
                ('instagram_link_url', models.CharField(blank=True, help_text='Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).', max_length=200)),
                ('name', models.CharField(max_length=20)),
                ('ocupation', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('aprove', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='About_us_team_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='About_us_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='About_us_top_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Top_section/')),
                ('years_of_experience', models.CharField(max_length=2)),
                ('no_of_events', models.CharField(max_length=3)),
                ('major_title', models.CharField(max_length=30)),
                ('major_description', models.CharField(blank=True, max_length=255)),
                ('minor_title1', models.CharField(max_length=30)),
                ('minor_description1', models.CharField(blank=True, max_length=255)),
                ('minor_title2', models.CharField(max_length=30)),
                ('minor_description2', models.CharField(blank=True, max_length=255)),
                ('comment1', models.CharField(blank=True, max_length=100)),
                ('comment2', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_one', models.CharField(max_length=50)),
                ('tab_two', models.CharField(max_length=50)),
                ('tab_three', models.CharField(max_length=50)),
                ('tab_four', models.CharField(max_length=50)),
                ('tab_five', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='blog_top_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_top_image')),
                ('image_description_major', models.CharField(max_length=100)),
                ('image_description_minor', models.CharField(blank=True, max_length=255)),
                ('image_profile', models.ImageField(upload_to='blog_top_image_profile')),
                ('profile_name', models.CharField(max_length=50)),
                ('profile_occupation', models.CharField(max_length=50)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('time_posted', models.TimeField(blank=True, null=True)),
                ('aprove', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePage_Category_Bottom_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='homepage_Posts/')),
                ('title1', models.CharField(max_length=200)),
                ('link_url', models.CharField(blank=True, help_text='Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).', max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('image2', models.ImageField(upload_to='homepage_Posts/')),
                ('title2', models.CharField(max_length=200)),
                ('time', models.TimeField(blank=True, null=True)),
                ('aprove', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_Category_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='homepage_category_sections/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='homepage_category_sections/')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('link_url1', models.CharField(blank=True, help_text='Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).', max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('time', models.TimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=20)),
                ('aprove', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_Category_Side_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage_category_side_section/')),
                ('title', models.CharField(max_length=100)),
                ('link_url', models.CharField(blank=True, help_text='Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).', max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('aprove', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage_images/')),
                ('small_title', models.CharField(max_length=15)),
                ('large_title', models.CharField(max_length=60)),
                ('link_url', models.CharField(blank=True, help_text='Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).', max_length=200)),
                ('event_date', models.DateField(blank=True, help_text='Optional: Date of the event if applicable.', null=True)),
                ('event_location', models.CharField(blank=True, help_text='Optional', max_length=255)),
                ('event_time', models.TimeField(blank=True, help_text='Optional', null=True)),
                ('aprove', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_Posts_Bottom_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage_Posts_Bottom_Section/')),
                ('title', models.CharField(max_length=200)),
                ('hoster_name', models.CharField(max_length=20)),
                ('descriptive_title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('link_url', models.CharField(blank=True, help_text='Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).', max_length=200)),
                ('aprove', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_Posts_Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage_Posts_Main/')),
                ('day', models.CharField(help_text='e.g., 12', max_length=10)),
                ('month', models.CharField(help_text='e.g., Dec', max_length=10)),
                ('small_title', models.CharField(max_length=20)),
                ('large_title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=700)),
                ('hoster_name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=10)),
                ('link_url', models.CharField(blank=True, help_text='Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).', max_length=200)),
                ('aprove', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_Posts_Side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage_Posts_Side/')),
                ('date', models.DateField(blank=True, null=True)),
                ('major_title', models.CharField(max_length=200)),
                ('descriptive_title', models.CharField(blank=True, max_length=255)),
                ('link_url', models.CharField(blank=True, help_text='Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).', max_length=200)),
                ('aprove', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_Sliding_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='homepage_sliding_images/')),
                ('category', models.CharField(max_length=15)),
                ('image2', models.ImageField(upload_to='homepage_sliding_images/')),
                ('small_title', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('link_url1', models.CharField(blank=True, help_text='Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).', max_length=200)),
                ('description', models.TextField(blank=True, verbose_name='Optional: A brief description of the image or event.')),
                ('time', models.TimeField(blank=True, null=True)),
                ('link_url2', models.CharField(blank=True, help_text='Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).', max_length=200)),
                ('aprove', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tab_five',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tab_five_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('aprove', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tab_four',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('point_one', models.CharField(max_length=60)),
                ('point_two', models.CharField(max_length=60)),
                ('point_three', models.CharField(max_length=60)),
                ('point_four', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='tab_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_description', models.CharField(max_length=300)),
                ('minor_description', models.CharField(blank=True, max_length=255)),
                ('quote', models.CharField(blank=True, max_length=255)),
                ('quote_author', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tab_three',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tab_three_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tab_three_images/')),
                ('image_title', models.CharField(blank=True, max_length=20)),
                ('image_description', models.CharField(blank=True, max_length=80)),
                ('aprove', models.BooleanField(default=False)),
            ],
        ),
    ]
