# Generated by Django 5.1.6 on 2025-09-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="link_url",
            field=models.CharField(
                blank=True,
                help_text="Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).",
                max_length=200,
            ),
        ),
    ]
