# Generated by Django 4.2.23 on 2026-06-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("short_description", models.CharField(max_length=300)),
                ("full_description", models.TextField()),
                ("image", models.ImageField(upload_to="appeals/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Food", "Food"),
                            ("Water", "Water"),
                            ("Healthcare", "Healthcare"),
                            ("Education", "Education"),
                            ("Emergency", "Emergency"),
                            ("General", "General"),
                        ],
                        default="General",
                        max_length=50,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("Most in Need", "Most in Need"),
                            ("Gaza", "Gaza"),
                            ("Syria", "Syria"),
                            ("Tanzania", "Tanzania"),
                            ("Sudan", "Sudan"),
                            ("Afghanistan", "Afghanistan"),
                        ],
                        default="Most in Need",
                        max_length=50,
                    ),
                ),
                ("goal_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "raised_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_urgent", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("aprove", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
