# Generated by Django 5.1.6 on 2025-09-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_homepage_link_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage_Sliding_Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image1", models.ImageField(upload_to="homepage_sliding_images/")),
                ("category", models.CharField(max_length=15)),
                ("image2", models.ImageField(upload_to="homepage_sliding_images/")),
                ("small_title", models.CharField(max_length=30)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "link_url1",
                    models.CharField(
                        blank=True,
                        help_text="Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).",
                        max_length=200,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("time", models.TimeField(blank=True, null=True)),
                (
                    "link_url2",
                    models.CharField(
                        blank=True,
                        help_text="Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).",
                        max_length=200,
                    ),
                ),
                ("aprove", models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name="HomePage",
            new_name="HomePage_Image",
        ),
    ]
