# Generated by Django 4.2.23 on 2026-06-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_appeal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appeal",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
