# Generated by Django 5.1.6 on 2025-09-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_homepage_sliding_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage_Category_Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="homepage_category_sections/"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="homepage_category_sections/"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "link_url1",
                    models.CharField(
                        blank=True,
                        help_text="Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).",
                        max_length=200,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("time", models.TimeField(blank=True, null=True)),
                ("comment", models.CharField(blank=True, max_length=20)),
                ("aprove", models.BooleanField(default=False)),
            ],
        ),
    ]
