# Generated by Django 4.2.23 on 2026-06-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_appeal_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppealImpact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="appeal_impacts/")),
                (
                    "stat_number",
                    models.CharField(
                        blank=True, help_text="e.g. 500, 1,200+", max_length=50
                    ),
                ),
                (
                    "stat_label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Families Fed, Students Supported",
                        max_length=100,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("aprove", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
