# Generated by Django 5.1.6 on 2025-09-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_homepage_category_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage_Category_Side_Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="homepage_category_side_section/"),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).",
                        max_length=200,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("aprove", models.BooleanField(default=False)),
            ],
        ),
    ]
