# Generated by Django 5.1.6 on 2025-09-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_homepage_category_side_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage_Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image1", models.ImageField(upload_to="homepage_Posts/")),
                ("title1", models.CharField(max_length=200)),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).",
                        max_length=200,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("image2", models.ImageField(upload_to="homepage_Posts/")),
                ("title2", models.CharField(max_length=200)),
                ("time", models.TimeField(blank=True, null=True)),
                ("aprove", models.BooleanField(default=False)),
            ],
        ),
    ]
