# Generated by Django 5.1.6 on 2025-09-11 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_homepage_posts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HomePage_Posts",
            new_name="HomePage_Category_Bottom_Section",
        ),
    ]
