# Generated by Django 5.1.6 on 2025-09-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_rename_homepage_posts_homepage_category_bottom_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage_Posts_Main",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="homepage_Posts_Main/")),
                ("day", models.CharField(help_text="e.g., 12", max_length=10)),
                ("month", models.CharField(help_text="e.g., Dec", max_length=10)),
                ("small_title", models.CharField(max_length=20)),
                ("large_title", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("hoster_name", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=10)),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).",
                        max_length=200,
                    ),
                ),
                ("aprove", models.BooleanField(default=False)),
            ],
        ),
    ]
