# Generated by Django 5.1.6 on 2025-09-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_homepage_posts_main"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage_Posts_Side",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="homepage_Posts_Side/")),
                ("date", models.DateField(blank=True, null=True)),
                ("major_title", models.CharField(max_length=200)),
                ("descriptive_title", models.CharField(blank=True, max_length=255)),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).",
                        max_length=200,
                    ),
                ),
                ("aprove", models.BooleanField(default=False)),
            ],
        ),
    ]
