# Generated by Django 5.1.6 on 2025-09-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_homepage_posts_side"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage_Posts_Bottom_Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="homepage_Posts_Bottom_Section/"),
                ),
                ("title", models.CharField(max_length=200)),
                ("hoster_name", models.CharField(max_length=20)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).",
                        max_length=200,
                    ),
                ),
                ("aprove", models.BooleanField(default=False)),
            ],
        ),
    ]
