# Generated by Django 5.1.6 on 2025-09-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_homepage_posts_bottom_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="About_us_title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
