# Generated by Django 5.1.6 on 2025-09-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_about_us_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="About_us_team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="About_us_team/")),
                (
                    "linkedin_link_url",
                    models.CharField(
                        blank=True,
                        help_text="Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).",
                        max_length=200,
                    ),
                ),
                (
                    "twitter_link_url",
                    models.CharField(
                        blank=True,
                        help_text="Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).",
                        max_length=200,
                    ),
                ),
                (
                    "instagram_link_url",
                    models.CharField(
                        blank=True,
                        help_text="Optional: For an external link, enter the full URL (e.g., https://example.com). For an internal link, enter the path (e.g., /about/).",
                        max_length=200,
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("ocupation", models.CharField(max_length=20)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("aprove", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="About_us_team_title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
