# Generated by Django 5.1.6 on 2025-09-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_about_us_team_about_us_team_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Top_section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="Top_section/")),
                ("years_of_experience", models.CharField(max_length=2)),
                ("no_of_events", models.CharField(max_length=3)),
                ("major_title", models.CharField(max_length=30)),
                ("major_description", models.CharField(blank=True, max_length=255)),
                ("minor_title1", models.CharField(max_length=30)),
                ("minor_description1", models.CharField(blank=True, max_length=255)),
                ("minor_title2", models.CharField(max_length=30)),
                ("minor_description2", models.CharField(blank=True, max_length=255)),
                ("comment1", models.CharField(blank=True, max_length=100)),
                ("comment2", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
