# Generated by Django 5.1.6 on 2025-09-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_top_section"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Top_section",
            new_name="About_us_top_section",
        ),
    ]
