# Generated by Django 5.1.6 on 2025-12-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0014_rename_top_section_about_us_top_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="blog_top_image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="blog_top_image")),
                ("image_description_major", models.CharField(max_length=100)),
                (
                    "image_description_minor",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "image_profile",
                    models.ImageField(upload_to="blog_top_image_profile"),
                ),
                ("profile_name", models.CharField(max_length=50)),
                ("profile_occupation", models.CharField(max_length=50)),
                ("date_posted", models.DateField(blank=True, null=True)),
                ("time_posted", models.TimeField(blank=True, null=True)),
                ("aprove", models.BooleanField(default=False)),
            ],
        ),
    ]
