# Generated by Django 5.1.6 on 2025-12-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0015_blog_top_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article_tab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tab_one", models.CharField(max_length=50)),
                ("tab_two", models.CharField(max_length=50)),
                ("tab_three", models.CharField(max_length=50)),
                ("tab_four", models.CharField(max_length=50)),
                ("tab_five", models.CharField(max_length=50)),
                ("tab_six", models.CharField(max_length=50)),
            ],
        ),
    ]
