# Generated by Django 5.1.6 on 2025-12-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0016_article_tab"),
    ]

    operations = [
        migrations.CreateModel(
            name="tab_one",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("major_description", models.CharField(max_length=255)),
                ("minor_description", models.CharField(blank=True, max_length=255)),
                ("quote", models.CharField(blank=True, max_length=255)),
                ("quote_author", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
