# Generated by Django 5.1.6 on 2025-12-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0017_tab_one"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tab_one",
            name="major_description",
            field=models.CharField(max_length=300),
        ),
    ]
