# Generated by Django 5.1.6 on 2025-12-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0018_alter_tab_one_major_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="tab_two",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="tab_two_images/")),
                ("image_description", models.CharField(blank=True, max_length=80)),
                ("image_explanation", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
