# Generated by Django 5.1.6 on 2025-12-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0019_tab_two"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tab_two",
            name="image_explanation",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
