# Generated by Django 5.1.6 on 2025-12-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0020_alter_tab_two_image_explanation"),
    ]

    operations = [
        migrations.CreateModel(
            name="tab_three",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                ("description", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="tab_three_images/")),
                ("image_title", models.CharField(blank=True, max_length=20)),
                ("image_description", models.CharField(blank=True, max_length=80)),
            ],
        ),
    ]
