# Generated by Django 5.1.6 on 2025-12-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0021_tab_three"),
    ]

    operations = [
        migrations.AddField(
            model_name="tab_three",
            name="approve",
            field=models.BooleanField(default=False),
        ),
    ]
