# Generated by Django 5.1.6 on 2025-12-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0022_tab_three_approve"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tab_three",
            old_name="approve",
            new_name="aprove",
        ),
    ]
