# Generated by Django 5.1.6 on 2025-12-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0023_rename_approve_tab_three_aprove"),
    ]

    operations = [
        migrations.CreateModel(
            name="tab_three_post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="tab_three_images/")),
                ("image_title", models.CharField(blank=True, max_length=20)),
                ("image_description", models.CharField(blank=True, max_length=80)),
                ("aprove", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="tab_three",
            name="aprove",
        ),
        migrations.RemoveField(
            model_name="tab_three",
            name="image",
        ),
        migrations.RemoveField(
            model_name="tab_three",
            name="image_description",
        ),
        migrations.RemoveField(
            model_name="tab_three",
            name="image_title",
        ),
    ]
