# Generated by Django 5.1.6 on 2025-12-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0024_tab_three_post_remove_tab_three_aprove_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="tab_four",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
                ("point_one", models.CharField(max_length=20)),
                ("point_two", models.CharField(max_length=20)),
                ("point_three", models.CharField(max_length=20)),
                ("point_four", models.CharField(max_length=20)),
            ],
        ),
    ]
