# Generated by Django 5.1.6 on 2025-12-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0025_tab_four"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tab_four",
            name="point_four",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="tab_four",
            name="point_one",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="tab_four",
            name="point_three",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="tab_four",
            name="point_two",
            field=models.CharField(max_length=40),
        ),
    ]
