# Generated by Django 5.1.6 on 2025-12-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0027_alter_tab_four_point_four_alter_tab_four_point_one_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tab_four",
            name="point_four",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="tab_four",
            name="point_one",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="tab_four",
            name="point_three",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="tab_four",
            name="point_two",
            field=models.CharField(max_length=60),
        ),
    ]
