# Generated by Django 5.1.6 on 2025-12-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0028_alter_tab_four_point_four_alter_tab_four_point_one_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="tab_five",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="tab_five_post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=80)),
                ("aprove", models.BooleanField(default=False)),
            ],
        ),
    ]
