# Generated by Django 5.1.6 on 2025-12-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0029_tab_five_tab_five_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tab_five_post",
            name="title",
            field=models.CharField(max_length=40),
        ),
    ]
