# Generated by Django 5.1.6 on 2025-12-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0030_alter_tab_five_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tab_five_post",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
