# Generated by Django 5.1.6 on 2025-12-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0031_alter_tab_five_post_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article_tab",
            name="tab_six",
        ),
    ]
