# Generated by Django 4.2.23 on 2026-01-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0032_remove_article_tab_tab_six"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage_sliding_image",
            name="description",
            field=models.TextField(
                blank=True,
                verbose_name="Optional: A brief description of the image or event.",
            ),
        ),
    ]
