# Generated by Django 4.2.23 on 2026-01-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0033_alter_homepage_sliding_image_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="tab_two",
        ),
        migrations.AddField(
            model_name="homepage_sliding_image",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
