# Generated by Django 4.2.23 on 2026-01-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0034_delete_tab_two_homepage_sliding_image_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="tab_seven",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="tab_six",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name="homepage_sliding_image",
            name="slug",
        ),
        migrations.AddField(
            model_name="article_tab",
            name="tab_seven",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="article_tab",
            name="tab_six",
            field=models.CharField(default="", max_length=50),
        ),
    ]
