# Generated by Django 6.0.1 on 2026-01-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_delete_tab_two_homepage_sliding_image_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage_sliding_image',
            name='slug',
        ),
        migrations.AlterField(
            model_name='homepage_category_bottom_section',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='homepage_category_section',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='homepage_posts_bottom_section',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
