# Generated by Django 4.2.23 on 2026-01-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0035_tab_seven_tab_six_remove_homepage_sliding_image_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage_posts_side",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
