# Generated by Django 4.2.23 on 2026-01-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0036_homepage_posts_side_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage_posts_side",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
