# Generated by Django 4.2.23 on 2026-02-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0037_alter_homepage_posts_side_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="tab_eight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name="article_tab",
            name="tab_eight",
            field=models.CharField(default="", max_length=50),
        ),
    ]
