# Generated by Django 4.2.23 on 2026-02-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0039_tab_nine_article_tab_tab_nine"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage_posts_bottom_section",
            name="descriptive_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="homepage_posts_bottom_section",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
