# Generated by Django 4.2.23 on 2026-02-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0040_homepage_posts_bottom_section_descriptive_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="homepage_image",
            name="large_title",
            field=models.CharField(max_length=60),
        ),
    ]
