# Generated by Django 4.2.23 on 2026-02-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0035_remove_homepage_sliding_image_slug_and_more"),
        ("pages", "0041_contactmessage_alter_homepage_image_large_title"),
    ]

    operations = []
