# Generated by Django 4.2.23 on 2026-02-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0042_merge_20260202_2224"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage_posts_bottom_section",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage_posts_bottom_section",
            name="descriptive_title",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
