# Generated by Django 4.2.23 on 2026-02-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0043_alter_homepage_posts_bottom_section_description_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="tab_eight",
        ),
        migrations.DeleteModel(
            name="tab_nine",
        ),
        migrations.DeleteModel(
            name="tab_seven",
        ),
        migrations.DeleteModel(
            name="tab_six",
        ),
        migrations.RemoveField(
            model_name="article_tab",
            name="tab_eight",
        ),
        migrations.RemoveField(
            model_name="article_tab",
            name="tab_nine",
        ),
        migrations.RemoveField(
            model_name="article_tab",
            name="tab_seven",
        ),
        migrations.RemoveField(
            model_name="article_tab",
            name="tab_six",
        ),
    ]
