# Generated by Django 6.0.1 on 2026-02-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_delete_tab_eight_delete_tab_nine_delete_tab_seven_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us_division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('aprove', models.BooleanField(default=False)),
            ],
        ),
    ]
