# Generated by Django 6.0.1 on 2026-07-04 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('is_organization', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, choices=[('Most in Need', 'Most in Need'), ('Gaza', 'Gaza'), ('Syria', 'Syria'), ('Tanzania', 'Tanzania')], default='', max_length=50)),
                ('postcode', models.CharField(blank=True, default='', max_length=20)),
                ('donation_type', models.CharField(choices=[('General Fund', 'General Fund'), ('Qurban', 'Qurban'), ('FundProject', 'FundProject'), ('Sadakah', 'Sadakah')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_country', models.CharField(choices=[('Most in Need', 'Most in Need'), ('Gaza', 'Gaza'), ('Syria', 'Syria'), ('Tanzania', 'Tanzania')], max_length=50)),
                ('to_provide', models.CharField(choices=[('Social Service', 'Social Service'), ('Education Center', 'Education Center'), ('Waqfu', 'Waqfu'), ('TSDF', 'TSDF')], max_length=50)),
                ('age_confirmation', models.BooleanField(default=False)),
                ('contact_email', models.BooleanField(default=False)),
                ('contact_sms', models.BooleanField(default=False)),
                ('contact_whatsapp', models.BooleanField(default=False)),
                ('contact_post', models.BooleanField(default=False)),
                ('gift_aid', models.BooleanField(default=False)),
                ('card_number', models.CharField(blank=True, default='', max_length=16)),
                ('expiry_date', models.CharField(blank=True, default='', max_length=5)),
                ('security_code', models.CharField(blank=True, default='', max_length=4)),
                ('agree_to_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('giving_frequency', models.CharField(choices=[('one-off', 'One-off'), ('every-day', 'Every Day'), ('every-friday', 'Every Friday'), ('every-month', 'Every Month')], default='one-off', max_length=20)),
                ('payment_method', models.CharField(default='mobile', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('provider', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('status', models.CharField(choices=[('created', 'Created'), ('initiated', 'Initiated'), ('pending', 'Pending'), ('retrying', 'Retrying'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('error', 'Error')], db_index=True, default='created', max_length=16)),
                ('gateway_reference', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('gateway_status', models.CharField(blank=True, default='', max_length=64)),
                ('gateway_message', models.TextField(blank=True, default='')),
                ('callback_hash', models.CharField(blank=True, default='', max_length=64)),
                ('callback_verified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiation_attempts', models.PositiveIntegerField(default=0)),
                ('last_initiation_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='donations.donation')),
            ],
        ),
        migrations.CreateModel(
            name='AzamPayWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_hash', models.CharField(db_index=True, max_length=64)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('gateway_reference', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('verification_passed', models.BooleanField(default=False)),
                ('duplicate', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('processing_note', models.CharField(blank=True, default='', max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='donations.paymenttransaction')),
            ],
        ),
    ]
