# Generated by Django 6.0.1 on 2026-07-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='country',
            field=models.CharField(blank=True, choices=[('Most in Need', 'Most in Need'), ('Gaza', 'Zanzibar'), ('Syria', 'Dar es salaam'), ('Tanzania', 'Morogoro')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='in_country',
            field=models.CharField(choices=[('Most in Need', 'Most in Need'), ('Gaza', 'Zanzibar'), ('Syria', 'Dar es salaam'), ('Tanzania', 'Morogoro')], max_length=50),
        ),
    ]
