# Generated by Django 4.2.23 on 2026-06-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0004_track_legacy_donation_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="donation_type",
            field=models.CharField(
                choices=[
                    ("General Fund", "General Fund"),
                    ("Qurban", "Qurban"),
                    ("FundProject", "FundProject"),
                    ("Sadakah", "Sadakah"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="giving_frequency",
            field=models.CharField(
                choices=[
                    ("one-off", "One-off"),
                    ("every-day", "Every Day"),
                    ("every-friday", "Every Friday"),
                    ("every-month", "Every Month"),
                ],
                default="one-off",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="to_provide",
            field=models.CharField(
                choices=[
                    ("Social Service", "Social Service"),
                    ("Education Center", "Education Center"),
                    ("Waqfu", "Waqfu"),
                    ("TSDF", "TSDF"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("initiated", "Initiated"),
                    ("pending", "Pending"),
                    ("retrying", "Retrying"),
                    ("processing", "Processing"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("error", "Error"),
                ],
                db_index=True,
                default="created",
                max_length=16,
            ),
        ),
    ]
